// Automatically generated by astro-icon
// b5e33011daffa3cee1e3b08922cc6ea595d0bbe8892aa8d79cdf507a502f5ad0

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "backendIcons/Bash"
		| "backendIcons/Express"
		| "backendIcons/Git"
		| "backendIcons/MongoDB"
		| "backendIcons/MySql"
		| "backendIcons/Node"
		| "backendIcons/Postman"
		| "collborate"
		| "contact/email"
		| "contact/location"
		| "contact/phone"
		| "explore"
		| "frontendIcons/astro"
		| "frontendIcons/Bootstrap"
		| "frontendIcons/CSS"
		| "frontendIcons/HTML"
		| "frontendIcons/JS"
		| "frontendIcons/React"
		| "frontendIcons/Redux"
		| "frontendIcons/Sass"
		| "frontendIcons/TailwindCSS"
		| "frontendIcons/Vue"
		| "innovate"
		| "social/github"
		| "social/linkedin"
		| "UpArrow";
}