// Automatically generated by astro-icon
// 5fe1336af4ea859bceda85187d095a840fcd1c2de19008773829ed654484e899

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "backendIcons/Bash"
		| "backendIcons/Express"
		| "backendIcons/Git"
		| "backendIcons/MongoDB"
		| "backendIcons/MySql"
		| "backendIcons/Node"
		| "backendIcons/Postman"
		| "collborate"
		| "contact/email"
		| "contact/location"
		| "contact/phone"
		| "explore"
		| "frontendIcons/astro"
		| "frontendIcons/Bootstrap"
		| "frontendIcons/CSS"
		| "frontendIcons/HTML"
		| "frontendIcons/JS"
		| "frontendIcons/Nextjs"
		| "frontendIcons/React"
		| "frontendIcons/Redux"
		| "frontendIcons/Sass"
		| "frontendIcons/TailwindCSS"
		| "frontendIcons/Vue"
		| "innovate"
		| "social/github"
		| "social/linkedin"
		| "UpArrow";
}